# Use an official Python runtime as a parent image
FROM python:3.13-bookworm

RUN apt-get update && apt-get install -y \
    build-essential \
    curl \
    software-properties-common \
    git \
    ffmpeg

# Set the working directory in the container
WORKDIR /app

# Clone the package from GitHub
# Update the number to manually pull the latest version. See
# https://stackoverflow.com/questions/27529191/how-to-update-code-from-git-to-a-docker-container
RUN echo '1' >/dev/null && git clone https://github.com/jhorzek/tellme.git /app/tellme

# Change to the repository directory
WORKDIR /app/tellme

# The project requires poetry
RUN pip install poetry
RUN poetry install

# Ensure the virtual environment is activated for subsequent commands
SHELL ["/bin/bash", "-c"]
RUN echo "source \$(poetry env info --path)/bin/activate" >> ~/.bashrc

EXPOSE 8501

HEALTHCHECK CMD curl --fail http://localhost:8501/_stcore/health

# Run the Streamlit application within the virtual environment
ENTRYPOINT ["poetry", "run", "streamlit", "run", "tellme/A_user_interface/streamlit_UI.py", "--server.port=8501", "--server.address=0.0.0.0"]